development:
  adapter: postgresql
  encoding: unicode
  database: startups_news_development
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: startups_news_test
  pool: 5
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: startups_news_production
  pool: 5
  host: localhost
