development:
  adapter: postgresql
  encoding: unicode
  database: startups_news_development
  username: postgres
  password: postgres
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: startups_news_test
  username: postgres
  password: postgres
  pool: 5
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: startups_news_production
  pool: 5
  host: localhost
